name: "Group of 3 action"
description: "Check if groups follow the requirements regarding number of members"
inputs:
  github-token:
    default: ${{ github.token }}
    required: true
  payload:
    description: "Json payload of information in the pull request"
    required: true
  filesAdded:
    description: "The added files in the pull request"
    required: true
  filesChanged:
    description: "The changed files in the pull request"
    required: true
  validTasks:
    description: "The tasks available to choose from"
    required: true
    default: course-automation/demo/essay/executable-tutorial/feedback/open-source/presentation
  validTasksGroupThree:
    description: "The tasks available to choose from for groups of 3"
    required: true
    default: demo/essay/open-source
runs: 
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.payload }}
    - ${{ inputs.filesAdded}}
    - ${{ inputs.filesChanged}}
    - ${{ inputs.validTasks }}
    - ${{ inputs.validTasksGroupThree }}